driver:
  name: vagrant
  customize:
    cpus: 2
    memory: 4096

provisioner:
  name: chef_zero

platforms:
  - name: windows-2008r2
    driver_config:
      box: chef/windows-server-2008r2-standard
  - name: windows-2012r2
    driver_config:
      box: chef/windows-server-2012r2-standard

suites:
  - name: default
    run_list:
      - recipe[webpi::default]
